# Generated by Django 5.2.3 on 2025-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
