# Generated by Django 5.2.3 on 2025-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_datasetuploadmodel_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
