# Generated by Django 5.2.3 on 2025-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_datasetuploadmodel_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Completed', 'completed')], max_length=255, null=True),
        ),
    ]
