# Generated by Django 5.2.3 on 2025-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_datasetuploadmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Completed', 'completed')], default='Pending', max_length=255, null=True),
        ),
    ]
