# Generated by Django 5.2.3 on 2025-11-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_datasetuploadmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='top_candidate_charts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='Pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
