# Generated by Django 5.2.3 on 2025-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_datasetuploadmodel_top_candidate_charts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=255, null=True),
        ),
    ]
