# Generated by Django 5.2.3 on 2025-11-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_datasetuploadmodel_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='context',
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='recommendations',
        ),
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.datasetuploadmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
