# Generated by Django 5.2.3 on 2025-11-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_datasetuploadmodel_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
