# Generated by Django 6.0 on 2025-12-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_datasetuploadmodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='chart_labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='patterns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='useful_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_contexts', to='pages.datasetuploadmodel'),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=255, null=True),
        ),
    ]
