# Generated by Django 6.0 on 2025-12-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_datasetuploadmodel_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetuploadmodel',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
