# Generated by Django 6.0 on 2025-12-12 19:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_datasetuploadmodel_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetuploadmodel',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='usercontext',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='chart_labels',
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='features',
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='patterns',
        ),
        migrations.RemoveField(
            model_name='datasetuploadmodel',
            name='useful_columns',
        ),
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='file',
            field=models.FileField(upload_to='uploads/datasets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='datasetuploadmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercontext',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='datasetuploadmodel',
            index=models.Index(fields=['user', '-uploaded_at'], name='pages_datas_user_id_906b3e_idx'),
        ),
    ]
